[package]
name = "trolly"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = { version = "0.6.2", default-features = false }
ctrlc = "3.2.3"
futures-util = "0.3.21"
log = "0.4.17"
tokio = { version = "1.20.1", features = ["rt", "macros"] }
tokio-tungstenite = { version = "0.18", features = ["native-tls-vendored"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
url = "2.2.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
