services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: trolly-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data:/var/lib/clickhouse
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      CLICKHOUSE_DB: trolly
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
