name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          # A directory to store and save the cache
          path: ./target
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build
        run: cargo build --verbose
        if: ${{ success() }}

      - name: Run tests
        run: cargo test --verbose

      - name: Build Docker image
        run: docker build -t my-image .
